#!/bin/bash

# Check for dependencies
command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
command -v cockpit-bridge >/dev/null 2>&1 || { echo >&2 "I require cockpit but it's not installed.  Aborting."; exit 1; }


# Remove container if exists
docker rm -f cockpit-docker

# Remove old build 
rm -rf ./dist ; mkdir ./dist

# Prep build folder
mkdir -p $PWD/dist/docker

# Build 
docker build -t local/cockpit-docker:latest .

# Build
docker run -it -v $PWD:/app --name local/cockpit-docker:latest local/cockpit-docker:latest

# Remove user module dir
rm -rf $HOME/.local/share/cockpit/docker

# Link as user module
rm $PWD/dist/docker/*test*
mkdir -p ~/.local/share/cockpit
ln -snf $PWD/dist/docker $HOME/.local/share/cockpit/docker

echo "===> List of packages, if all went fine this list should container docker"
cockpit-bridge --packages
